on: pull_request
name: Pull requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PullRequestHandler
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: david.f.s.duque@tecnico.ulisboa.pt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
